rails_project/config/routes.rb
RailsProject::Application.routes.draw do

  namespace :admin do
    resources :roles
    resources :users
    root :to => "admin#index"
  end

  devise_for :users

  root :to => 'home#index'

end

rails_project/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

rails_project/app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles, :foreign_key => "role_id", :association_foreign_key => "user_id"
  belongs_to :resource, :polymorphic => true
  has_many :children, :class_name => "Role", :foreign_key => "parent_id"
  belongs_to :parent, :class_name => "Role"
end

rails_project/app/models/user.rb
class User < ActiveRecord::Base
  include Rolify::Roles
  # extend Rolify::Dynamic
  has_and_belongs_to_many :roles, :join_table => :users_roles, :foreign_key => "user_id", :association_foreign_key => "role_id"
  accepts_nested_attributes_for :roles

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role_ids

  def role
  	roles.first
  end

  def is?(specific_role)
    role == specific_role
  end

  def is_at_least?(specific_role)
    current_role = self.role
    begin
      if current_role.name == specific_role
        return true
      else
        current_role = current_role.parent
      end
    end while !current_role.nil?
    return false
  end

end

rails_project/app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
	before_filter :check_if_admin
	layout "admin/layouts/application"

	def index
	end

	private
	def check_if_admin
		unless current_user && current_user.is_at_least?("admin")
			redirect_to new_user_session_path, :notice => "You don't have the admin rights"
		end
	end


end

rails_project/app/controllers/admin/roles_controller.rb
class Admin::RolesController < Admin::AdminController
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.where :parent_id => nil

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    redirect_to admin_roles_path
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new
    @roles = Role.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
    @roles = Role.all
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to admin_roles_path, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to admin_roles_path, notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find_by_id(params[:id])
    unless @role.nil?
      @role.destroy
    end

    respond_to do |format|
      format.html { redirect_to admin_roles_url }
      format.json { head :no_content }
    end
  end
end

rails_project/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController

  # GET /admin/users
  def index
    @users = User.all
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
    redirect_to admin_users_path
  end

  # GET /admin/users/new
  def new
    @user = User.new
    @roles = Role.all
  end

  # GET /admin/users/1/edit
  def edit
    @user = User.find(params[:id])
    @roles = Role.all
  end
  
  # POST /admin/users
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_path, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        @roles = Role.all
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/users/1
  # PUT /admin/users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to admin_users_path, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @user = User.find_by_id(params[:id])
    unless @user.nil?
      @user.destroy
    end

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end
end

rails_project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

rails_project/app/controllers/home_controller.rb
class HomeController < ApplicationController
end

rails_project/app/helpers/application_helper.rb
module ApplicationHelper

  def controller_name
    params[:controller].split("/").last
  end

end

rails_project/app/helpers/home_helper.rb
module HomeHelper
end

rails_project/app/helpers/roles_helper.rb
module RolesHelper
end

rails_project/app/views/admin/admin/index.html.erb
<%= link_to 'Users', admin_users_path %>
<br/>
<%= link_to 'Roles', admin_roles_path %>

rails_project/app/views/admin/layouts/_menu.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container-fluid">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<a class="brand" href="#">Rais Project</a>
			<div class="nav-collapse">
				<ul class="nav">
					<li class="<%= "active" if controller_name == "admin" && controller.action_name == "index" %>"><%= link_to "Home", admin_root_path %></li>
					<li class="<%= "active" if controller_name == "users" %>"><%= link_to "Users", admin_users_path %></li>
					<li class="<%= "active" if controller_name == "roles" %>"><%= link_to "Roles", admin_roles_path %></li>
				</ul>
				<p class="navbar-text pull-right">Logged in as <%= link_to current_user.email, destroy_user_session_path, confirm: 'Log out?', method: :delete %></p>
			</div><!--/.nav-collapse -->
		</div>
	</div>
</div>

rails_project/app/views/admin/layouts/_sidebar.html.erb
<div class="span3">
	<div class="well sidebar-nav">
		<ul class="nav nav-list">
			<li class="nav-header">Sidebar</li>
			<li class="active"><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
			<li class="nav-header">Sidebar</li>
			<li><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
			<li class="nav-header">Sidebar</li>
			<li><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
		</ul>
	</div><!--/.well -->
</div><!--/span-->

rails_project/app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>RailsProject</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">

	<style type="text/css">
		body {
			padding-top: 60px;
			padding-bottom: 40px;
		}
		.sidebar-nav {
			padding: 9px 0;
		}
	</style>
	<%= stylesheet_link_tag    "application", :media => "all" %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
     	<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">

	<%= csrf_meta_tags %>
</head>
<body>

	<%= render "layouts/menu" %>

  <% unless notice.nil? %>
	  <p id="notice" class="alert"><%= notice %></p>
  <% end %>

  <div class="container-fluid">
    <!--<div class="row-fluid">-->

    <%= yield %>

      <!--
      <div class="span9">
        <div class="hero-unit">
          <h1>Hello, world!</h1>
          <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
          <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
        </div>
        <div class="row-fluid">
          <div class="span4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn" href="#">View details &raquo;</a></p>
          </div>
          <div class="span4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn" href="#">View details &raquo;</a></p>
          </div>
          <div class="span4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn" href="#">View details &raquo;</a></p>
          </div>
        </div>
        <div class="row-fluid">
          <div class="span4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn" href="#">View details &raquo;</a></p>
          </div>
          <div class="span4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn" href="#">View details &raquo;</a></p>
          </div>
          <div class="span4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn" href="#">View details &raquo;</a></p>
          </div>
        </div>
      </div>
    </div>-->

    <hr>

    <footer>
      <p>&copy; Company 2012</p>
    </footer>

  </div><!--/.fluid-container-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  	<%= javascript_include_tag "application" %>

</body>
</html>


    

rails_project/app/views/admin/roles/_form.html.erb
<%= form_for [:admin, @role] do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div><%= f.label :name %><br />
  <%= f.text_field :name %></div>

  <div>
    <%= f.label :parent %><br />
    <%= f.select :parent_id, @roles.map { |role|
      if role.nil?
        ["", ""]
      else
        [role.name, role.id]
      end
    }, :include_blank => true
    %>
  </div>

  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

rails_project/app/views/admin/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_roles_path %>

rails_project/app/views/admin/roles/index.html.erb
<div class="page-header">
  <h1>Listing roles <small><%= link_to 'New Role', new_admin_role_path %></small></h1>
</div>

<%

def display_roles_tree roles
  %>
  <ul>
    <%
    roles.each do |role|
      %>
      <li>
        <%= link_to role.name, edit_admin_role_path(role) %>
         - 
        <%= link_to 'Destroy', [:admin, role], confirm: 'Are you sure?', method: :delete %>
        <%
        if role.children.count > 0
          display_roles_tree role.children
        end
        %>
      </li>
      <%
    end
    %>
  </ul>
  <%
end

%>

<% display_roles_tree @roles %>

<br />

rails_project/app/views/admin/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_roles_path %>

rails_project/app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div><%= f.label :email %><br />
  <%= f.email_field :email %></div>
  
  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>

  <div>
    <%= f.label :role %><br />
    <% puts @user.roles.inspect %>
    <%= select_tag "user[role_ids][]", options_from_collection_for_select(@roles, "id", "name", @user.role.nil? ? nil : @user.role.id), :include_blank => true
    %>
  </div>

  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

rails_project/app/views/admin/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

rails_project/app/views/admin/users/index.html.erb
<div class="page-header">
  <h1>Listing users <small><%= link_to 'New User', new_admin_user_path %></small></h1>
</div>

<div class="row-fluid">
  <table class="table table-striped table-bordered table-condensed">
    <thead>
      <tr>
        <th>#</th>
        <th>Email</th>
        <th>Role</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>

      <%
      @users.each do |user|
        %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.email %></td>
          <td><%= user.role.name.humanize unless user.role.nil? %></td>
          <td>
            <%= link_to "Edit", edit_admin_user_path(user) %>
             - 
            <%= link_to 'Destroy', [:admin, user], confirm: 'Are you sure?', method: :delete %>
          </td>
        </tr>
        <%
      end
      %>

    </tbody>

  </table>
</div>

rails_project/app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

rails_project/app/views/layouts/_menu.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container-fluid">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<a class="brand" href="#">Rails Project</a>
			<div class="nav-collapse">
				<ul class="nav">
					<li class="<%= "active" if controller_name == "home" && controller.action_name == "index" %>"><%= link_to "Home", root_path %></li>
					<% if user_signed_in? && current_user.is_at_least?("admin") && current_user %>
						<li class="<%= "active" if controller_name == "admin" && controller.action_name == "index" %>"><%= link_to "Admin", admin_root_path %></li>
						<li class="<%= "active" if controller_name == "users" %>"><%= link_to "Users", admin_users_path %></li>
						<li class="<%= "active" if user_signed_in? && current_user.is_at_least?("admin") && controller_name == "roles" %>"><%= link_to "Roles", admin_roles_path %></li>
					<% end %>
				</ul>
				<p class="navbar-text pull-right">
					<% if !user_signed_in? %>
						<%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %>
					<% elsif current_user.is_at_least? "admin" %>
						Logged in as <%= link_to current_user.email, destroy_user_session_path, confirm: 'Log out?', method: :delete %>
					<% end %>
				</p>
				<p class="navbar-text pull-right"></p>
			</div><!--/.nav-collapse -->
		</div>
	</div>
</div>

rails_project/app/views/layouts/_sidebar.html.erb
<div class="span3">
	<div class="well sidebar-nav">
		<ul class="nav nav-list">
			<li class="nav-header">Sidebar</li>
			<li class="active"><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
			<li class="nav-header">Sidebar</li>
			<li><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
			<li class="nav-header">Sidebar</li>
			<li><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
		</ul>
	</div><!--/.well -->
</div><!--/span-->

rails_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>RailsProject</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">

	<style type="text/css">
		body {
			padding-top: 60px;
			padding-bottom: 40px;
		}
		.sidebar-nav {
			padding: 9px 0;
		}
	</style>
	<%= stylesheet_link_tag    "application", :media => "all" %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
     	<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">

	<%= csrf_meta_tags %>
</head>
<body>

	<%= render "layouts/menu" %>

  <% unless notice.nil? %>
    <p id="notice" class="alert"><%= notice %></p>
  <% end %>

  <div class="container-fluid">
    <!--<div class="row-fluid">-->

    <%= yield %>

      <!--

      <div class="span9">
        <div class="hero-unit">
          <h1>Hello, world!</h1>
          <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
          <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
        </div>
        <div class="row-fluid">
          <div class="span4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn" href="#">View details &raquo;</a></p>
          </div>
          <div class="span4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn" href="#">View details &raquo;</a></p>
          </div>
          <div class="span4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn" href="#">View details &raquo;</a></p>
          </div>
        </div>
        <div class="row-fluid">
          <div class="span4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn" href="#">View details &raquo;</a></p>
          </div>
          <div class="span4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn" href="#">View details &raquo;</a></p>
          </div>
          <div class="span4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn" href="#">View details &raquo;</a></p>
          </div>
        </div>
      </div>
    </div>-->

    <hr>

    <footer>
      <p>&copy; Company 2012</p>
    </footer>

  </div><!--/.fluid-container-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

</body>
</html>


    